name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 31337
    start_block: 0
    rpc_config:
      url: "http://127.0.0.1:8545"
    contracts:
      - name: TradePair
        address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
        handler: src/EventHandlers.ts
        abi_file_path: "abi/TradePair.json"
        events:
          - event: PositionOpened
            requiredEntities:
              - name: User
              - name: Position
