name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 1 # Ethereum Mainnet
    start_block: 10861674
    contracts:
      - name: ERC20
        address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984" #UNI
        handler: src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
            requiredEntities:
              - name: "Account"
              - name: "Approval"
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
            requiredEntities:
              - name: "Account"
              - name: "Approval"
      - name: TradePair
        address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
        handler: src/EventHandlers.ts
        abi_file_path: "abi/TradePair.json"
        events:
          - event: PositionOpened
            requiredEntities:
              - name: User
